// <auto-generated />
using System;
using ETS2Tachograph.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETS2Tachograph.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TachographDbContext))]
    [Migration("20260714234245_AddLayeredActivityRetention")]
    partial class AddLayeredActivityRetention
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.ActivityRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Activity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ActivitySessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Condition")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndGameMinuteExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchivedToWarm")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartGameMinute")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivitySessionId", "StartGameMinute")
                        .IsUnique();

                    b.ToTable("ActivityRecords", (string)null);
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.ActivityRetentionStateEntity", b =>
                {
                    b.Property<string>("DriverCardId")
                        .HasColumnType("TEXT");

                    b.Property<long>("HighWaterMarkGameMinute")
                        .HasColumnType("INTEGER");

                    b.HasKey("DriverCardId");

                    b.ToTable("ActivityRetentionStates", (string)null);
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.ActivitySessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverCardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAtGameMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAtGameMinute")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverCardId", "SessionIndex")
                        .IsUnique();

                    b.ToTable("ActivitySessions", (string)null);
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.DriverCardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverProfileId");

                    b.ToTable("DriverCards", (string)null);
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.DriverProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("DriverProfiles", (string)null);
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.FerryRestRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriverCardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EndGameMinuteExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterruptionCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InterruptionMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartGameMinute")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverCardId", "StartGameMinute");

                    b.ToTable("FerryRestRecords", (string)null);
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.RegulationSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ContinuousDrivingMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DailyDrivingMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriverCardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FortnightlyDrivingMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GameMinute")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinutesUntilBreak")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinutesUntilDailyRestDeadline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ViolationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("WeeklyDrivingMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverCardId", "GameMinute");

                    b.ToTable("RegulationSnapshots", (string)null);
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.TachographSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DrivingSpeedThresholdKph")
                        .HasColumnType("REAL");

                    b.Property<int>("WeekEpochOffsetDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TachographSettings", (string)null);
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.WarmActivityBlockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Activity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Condition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriverCardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndGameMinuteExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartGameMinute")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverCardId", "StartGameMinute")
                        .IsUnique();

                    b.ToTable("WarmActivityBlocks", (string)null);
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.ActivityRecordEntity", b =>
                {
                    b.HasOne("ETS2Tachograph.Infrastructure.Persistence.ActivitySessionEntity", "ActivitySession")
                        .WithMany("Records")
                        .HasForeignKey("ActivitySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivitySession");
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.ActivityRetentionStateEntity", b =>
                {
                    b.HasOne("ETS2Tachograph.Infrastructure.Persistence.DriverCardEntity", "DriverCard")
                        .WithMany()
                        .HasForeignKey("DriverCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverCard");
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.ActivitySessionEntity", b =>
                {
                    b.HasOne("ETS2Tachograph.Infrastructure.Persistence.DriverCardEntity", "DriverCard")
                        .WithMany("Sessions")
                        .HasForeignKey("DriverCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverCard");
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.DriverCardEntity", b =>
                {
                    b.HasOne("ETS2Tachograph.Infrastructure.Persistence.DriverProfileEntity", "DriverProfile")
                        .WithMany("Cards")
                        .HasForeignKey("DriverProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverProfile");
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.WarmActivityBlockEntity", b =>
                {
                    b.HasOne("ETS2Tachograph.Infrastructure.Persistence.DriverCardEntity", "DriverCard")
                        .WithMany()
                        .HasForeignKey("DriverCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverCard");
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.ActivitySessionEntity", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.DriverCardEntity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ETS2Tachograph.Infrastructure.Persistence.DriverProfileEntity", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
