<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETS2Tachograph.Application\ETS2Tachograph.Application.csproj" />
    <ProjectReference Include="..\ETS2Tachograph.Core\ETS2Tachograph.Core.csproj" />
    <ProjectReference Include="..\ETS2Tachograph.RuleEngine\ETS2Tachograph.RuleEngine.csproj" />
  </ItemGroup>

</Project>
